### ISSUE TITLE
Error when using AUK for Ebird

### ISSUE THREAD

**Issue by CamachoAndres** [CornellLabofOrnithology/auk#13] opened 2018-03-19 02:47 UTC
Hi,
I am working with AUK to extract presence/absence data from the EBD. I already cleaned both, the EBD and the Sampling data, nevertheless when I try to apply the filters I get the following message:
> filters <- auk_ebd(cleaned_EBD, file_sampling = cleaned) %>% 
+     auk_species("Timberline Wren") %>% 
+     auk_complete()
**Error in sub(re, "", x, perl = TRUE) : input string 1 is invalid UTF-8**
I've been looking on the internet for information but couldn't find anything useful.

Do you know what the problem is?

Best,

Andres

**Comment by mstrimas** [comment] 2018-03-19 06:58
Hi Andres,

I'm not able to reproduce your error. Could you try updating auk to the latest development version to see if that helps: `devtools::install_github("CornellLabofOrnithology/auk")`

If that doesn't help, you have three statements (`auk_ebd()`, `auk_species()`, and `auk_complete()`), can you let me know which one is causing the error?

Finally, please run `devtools::session_info()` and paste the results here.

Thanks!

**Comment by CamachoAndres** [comment] 2018-03-19 17:25
Hi Matt,

Thank you very much for your answer.

I tried updating auk, but get the same error message.
From the three statements I think that auk_ebd() is the one causing the
error. Isn't that step required to filter the data?

Here are the results from devtools::session_info()
> devtools::session_info()
Session info ---------------------------------------------------------
 setting  value
 version  R version 3.4.4 (2018-03-15)
 system   x86_64, darwin15.6.0
 ui       RStudio (1.1.442)
 language (EN)
 collate  C
 tz       America/Costa_Rica
 date     2018-03-19

Packages -------------------------------------------------------------
 package    * version date
 assertthat   0.2.0   2017-04-11
 auk        * 0.2.0   2018-03-19
 base       * 3.4.4   2018-03-15
 bindr        0.1.1   2018-03-13
 bindrcpp     0.2     2017-06-17
 compiler     3.4.4   2018-03-15
 curl         3.1     2017-12-12
 datasets   * 3.4.4   2018-03-15
 devtools   * 1.13.5  2018-02-18
 digest       0.6.15  2018-01-28
 dplyr        0.7.4   2017-09-28
 git2r        0.21.0  2018-01-04
 glue         1.2.0   2017-10-29
 graphics   * 3.4.4   2018-03-15
 grDevices  * 3.4.4   2018-03-15
 httr         1.3.1   2017-08-20
 magrittr     1.5     2014-11-22
 memoise      1.1.0   2017-04-21
 methods    * 3.4.4   2018-03-15
 pillar       1.2.1   2018-02-27
 pkgconfig    2.0.1   2017-03-21
 R6           2.2.2   2017-06-17
 Rcpp         0.12.16 2018-03-13
 rlang        0.2.0   2018-02-20
 stats      * 3.4.4   2018-03-15
 stringi      1.1.7   2018-03-12
 stringr      1.3.0   2018-02-19
 tibble       1.4.2   2018-01-22
 tools        3.4.4   2018-03-15
 utils      * 3.4.4   2018-03-15
 withr        2.1.2   2018-03-15
 source
 CRAN (R 3.4.0)
 Github (CornellLabofOrnithology/auk@0507ca5)
 local
 CRAN (R 3.4.1)
 CRAN (R 3.4.0)
 local
 CRAN (R 3.4.3)
 local
 CRAN (R 3.4.3)
 CRAN (R 3.4.3)
 CRAN (R 3.4.2)
 CRAN (R 3.4.3)
 CRAN (R 3.4.2)
 local
 local
 CRAN (R 3.4.1)
 CRAN (R 3.4.0)
 CRAN (R 3.4.0)
 local
 CRAN (R 3.4.3)
 CRAN (R 3.4.0)
 CRAN (R 3.4.0)
 CRAN (R 3.4.4)
 CRAN (R 3.4.3)
 local
 CRAN (R 3.4.4)
 CRAN (R 3.4.3)
 CRAN (R 3.4.3)
 local
 local
 CRAN (R 3.4.4)

Thanks again.

Andres

2018-03-19 0:58 GMT-06:00 Matt Strimas-Mackey <notifications@github.com>:

**Comment by mstrimas** [comment] 2018-03-19 17:55
What are `cleaned_EBD` and `cleaned` defined as?

**Comment by CamachoAndres** [comment] 2018-03-19 18:45
They are the result of the auk_clean function:

> sampling_data <-
"/Users/camach/Documents/Manuscritos/Highland_birds/ebd_sampling_relFeb-2018/ebd_sampling_relFeb-2018.txt.gz"
> f_out_sampling <- "sampling_cleaned.txt"
> cleaned_sampling <- auk_clean(sampling_data, f_out = f_out_sampling)

> ebd_data <-
"/Users/camach/Documents/Manuscritos/Highland_birds/ebd_relFeb-2018_COMPLETE/ebd_relFeb-2018.txt.gz"
> f_out_ebd <- "ebd_cleaned.txt"
> cleaned_ebd <- auk_clean(ebd_data, f_out = f_out_ebd)



2018-03-19 11:55 GMT-06:00 Matt Strimas-Mackey <notifications@github.com>:

**Comment by mstrimas** [comment] 2018-03-19 18:50
Your files end in `txt.gz` suggesting that they need to be unzipped. This is confusing because the EBD needs to be uncompressed **twice**. Also, `auk_clean()` should have returned an error, not sure what happened there. Try unzipping and re-running both the cleaning and filtering.

**Comment by mstrimas** [comment] 2018-03-19 18:50
Please let me know if this works so I can close the issue.

**Comment by CamachoAndres** [comment] 2018-03-20 05:40
Just to let you know, I'm still running the codes. Seems like it might
work, since the cleaning of the EDB file is taking way longer than before,
it's been like six hours. I'll let you know what happens tomorrow.

2018-03-19 12:50 GMT-06:00 Matt Strimas-Mackey <notifications@github.com>:

**Comment by mstrimas** [comment] 2018-03-22 16:00
@CamachoAndres did you make any progress on this?

**Comment by CamachoAndres** [comment] 2018-03-22 16:14
Hello,

Yes! It worked. Sorry it took so long but doing everything from scratch
took a long time. Actually I just finished doing the filtering step.
Zero-filling is taking forever. But yes, I was able to filter the data. One
quick question. Can I also do zero filling with a custom list (the ones you
can request from ebird).

Thanks

**Comment by mstrimas** [comment] 2018-03-22 16:55
Glad it worked!

How long is it taking you to run? For me it's about 3h to clean and 1.5-3h to filter on a new MacBook Pro, but I haven't timed it on other machines.

Yes, reading in the data and zero-filling can take a long time. How big are the files that came out of the filtering step?

At the moment you can't zero-fill the custom download files because they don't come with an associated sampling event data file, but we hope this will change.

**Comment by CamachoAndres** [comment] 2018-03-22 18:11
Thanks for all your help. It's taking a little longer than that, but my
MacBook Pro is three years old. The zero filling suddenly stopped at 89
percent. The size of the file is 506K, so I did not expect it to take this
long.

2018-03-22 10:55 GMT-06:00 Matt Strimas-Mackey <notifications@github.com>:

**Comment by mstrimas** [comment] 2018-03-22 18:20
With zero filling, the bottleneck is often the sampling event data. Even when the filtered EBD is small, the sampling event data can be quite large.

**Comment by CamachoAndres** [comment] 2018-03-22 18:32
Yes, the Sampling event data is 7.18GB.

2018-03-22 12:20 GMT-06:00 Matt Strimas-Mackey <notifications@github.com>:

**Comment by mstrimas** [comment] 2018-03-22 18:47
That's your problem, you'll never be able to zero fill that. I see what happened now, your sampling event data file includes every complete ebird checklist, which is 100s of millions, even though your species only occurs in Costa Rica. What you need to do is filter geographically as well:

```
filters <- auk_ebd(cleaned_EBD, file_sampling = cleaned) %>%
  auk_species("Timberline Wren") %>% 
  auk_country("Costa Rica") %>%
  auk_complete()
```

This will greatly reduce your sampling event file size. If your worried about loose some records that aren't in Costa Rica, you can add in some neighbouring countries too.

**Comment by CamachoAndres** [comment] 2018-03-22 18:49
Thank you so much! I’m sure it will work out now!

**Comment by CamachoAndres** [comment] 2018-03-24 15:07
I was able to extract all the Timberline Wren data and zero-fill it. Thank
you very much. Now I'm doing it for another species, but the filtering is
taking forever, and the CPU is zero, it's like R is not recognizing the
command or something. I've been struggling with that for two days now. I
have restarted the computer and re install R and Rsession.

2018-03-22 12:48 GMT-06:00 Andres Camacho <camacho.andr@gmail.com>:

> Thank you so much! I’m sure it will work out now!
>
> On Thu, Mar 22, 2018 at 12:47 PM Matt Strimas-Mackey <

**Comment by mstrimas** [comment] 2018-03-24 15:16
can you post the code for the filtering?

**Comment by CamachoAndres** [comment] 2018-03-24 15:24
I'm using the same one I used for the Timberline Wren but for the new
species. 'Cleaned_EBD' and "cleaned_sampling' are the same ones I used for
the Timberline Wren.
> setwd("~/Documents/Manuscritos/Highland_birds/R_files")
> load("~/Documents/Manuscritos/Highland_birds/R_files/AUK.RData")
> library(auk)
auk 0.2.0 functions with EBD files downloaded after March 15, 2018.
See ?auk_version_date for details.
> filters <- auk_ebd(cleaned_EBD, file_sampling = cleaned_sampling) %>%
+     auk_species("Volcano Junco") %>%
+     auk_country(c("Costa Rica", "Panama")) %>%
+     auk_complete()
> ebd_Junco_filtered <- auk_filter(filters,
+                                file = "Junco-filtered.txt",
+                                file_sampling =
"Junco-sampling-filtered.txt", overwrite =TRUE)


2018-03-24 9:16 GMT-06:00 Matt Strimas-Mackey <notifications@github.com>:

**Comment by mstrimas** [comment] 2018-03-26 11:17
Were you able to sort this out?

I'm not sure what's going on there, there's no reason why this shouldn't work if your Timberline Wren 
case did work. If you run `top` in the terminal, you should see awk running when you're filtering.

**Comment by CamachoAndres** [comment] 2018-03-27 12:55
Hi Matt, I don’t understand what happened, it’s all working now. Thanks for
all your help and patience. Also, thank you for such an useful package.

**Closed** 2018-03-27 15:07 UTC
